
FROM debian:latest

MAINTAINER Stan Velikov "stan@vip-consult.solutions"

ENV DEBIAN_FRONTEND noninteractive
ENV APT_LISTCHANGES_FRONTEND noninteractive

RUN curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash
